### ISSUE TITLE
Responsive framework eval

### ISSUE THREAD

**Issue by derektiffany** [productmindset/site#15]
Currently using:
Bulma https://bulma.io/

Lightweight / minimal responsive framework.  Seems to fit needs.  However, if there is a different framework that would work ... 

Perhaps worth considering:
UIKit https://getuikit.com/
Skeleton http://getskeleton.com/

**Comment by product-mindset** [comment]
Foundation could also be an option since it's used here:
https://www.3pillarglobal.com/

**Comment by derektiffany** [comment]
Sticking with Bulma unless we find reason to change
