### ISSUE TITLE
Standardize on yarn or npm

### ISSUE THREAD

**Issue by derektiffany** [productmindset/site#4]
It will be easy for `yarn.lock` and `package-lock.json` files to get out of sync.

**Comment by derektiffany** [comment]
Stackoverflow discussion:
https://stackoverflow.com/questions/44552348/should-i-commit-yarn-lock-and-package-lock-json-files

**Comment by CodyPredy** [comment]
How I see it... use `.npmrc` with:
```
save-exact = true
```

And avoid using ^ or * in the package.json. If you need a newer version then update the package.json.

**Comment by product-mindset** [comment]
@CodyPredy great idea to use `.npmrc` with `save-exact`.  Dependencies in [package.json](https://github.com/product-mindset/site/blob/master/package.json) have been pinned ... and [Renovate](https://renovateapp.com/) has been set up to yell if any are unpinned (^, *, ~, or other semvers)

**Comment by derektiffany** [comment]
Having both yarn and npm lock files (with Renovate) actually seems to work pretty well
