### ISSUE TITLE
DEV version of CMS build

### ISSUE THREAD

**Issue by product-mindset** [productmindset/site#48]
Follow on from #26 

Now that we can get a local CMS running with some manual editing ... would be nice to have a local DEV version automatically.  Ie, `yarn develop` could get a nice local version going.

Worth looking at:
https://www.gatsbyjs.org/docs/environment-variables/
https://github.com/netlify/netlify-cms/tree/master/src/backends/test-repo
https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/

**Comment by product-mindset** [comment]
See [here](https://github.com/product-mindset/site/blob/master/README.md#cms-development) for the manual steps to run the cms locally.

**Comment by derektiffany** [comment]
Deferred
